site_name: My site
site_url: https://mydomain.org/mysite
theme:
  name: material
nav:
  - Home: index.md
  - Experience: experience.md
  - Projects: projects.md
  - Blog:
    - Blog1: myblog1.md
    - Blog2: myblog2.md