site_name: FX Master Course
site_url: https://gustavodomenico.github.io/fx-master-course/
theme:
  name: material
  language: pt
nav:
  - Home: index.md
  - Experience: experience.md
extra:
  alternate:
    - name: Portuguese
      link: pt/ 
      lang: pt
    - name: English
      link: en/
      lang: en
plugins:
  - redirects:
      redirect_maps:
        'index.md': 'en/index.md'