site_name: FX Tutorial
site_url: https://gustavodomenico.github.io/
docs_dir: '../../docs/pt/'                           
site_dir: '../../../pt'    

theme:
  name: material
  language: pt
  include_homepage_in_sidebar: false
  features:
    - navigation.expand
nav:
  - Introdução: 
    - Definição: introduction/index.md
    - Ingressos e Remessas: introduction/currency-flow.md
    - Negociação: introduction/negotiation.md
  - Tipos e Modalidades: fx-types.md
  - Risco Cambial:
    - Fundamentos: risk/fundamentals.md
    - Instrumentos de Hedge: risk/hedging.md
    - Tesouraria corporativa: risk/corporate-treasury.md
    - Transferência de Risco: risk/risk-transfer.md
  - Casos de uso: use-cases.md

extra:
  alternate:
    - name: Portuguese
      link: https://gustavodomenico.github.io/pt/
      lang: pt
    - name: English
      link: https://gustavodomenico.github.io/en/
      lang: en
extra_css:
  - css/custom.css