site_name: FX Tutorial
site_url: https://gustavodomenico.github.io/
docs_dir: '../../docs/pt'                           
site_dir: '../../r/pt'    

theme:
  name: material
  language: pt
  include_homepage_in_sidebar: false
  features:
    - navigation.expand
nav:
  - Introdução: index.md
extra:
  alternate:
    - name: Portuguese
      link: https://gustavodomenico.github.io/r/pt/
      lang: pt
    - name: English
      link: https://gustavodomenico.github.io/r/en/
      lang: en