site_name: FX Trading 101
site_url: https://gustavodomenico.github.io/
docs_dir: '../../docs/en'                           
site_dir: '../../../en'    

theme:
  name: material
  language: en
  include_homepage_in_sidebar: false
  features:
    - navigation.expand
nav:
  - Introdução: index.md
extra:
  alternate:
    - name: Portuguese
      link: https://gustavodomenico.github.io/pt/
      lang: pt
    - name: English
      link: https://gustavodomenico.github.io/en/
      lang: en