site_name: FX Tutorial
site_url: https://gustavodomenico.github.io/
docs_dir: '../../docs/en'                           
site_dir: '../../r/en'    

theme:
  name: material
  language: en
  include_homepage_in_sidebar: false
  features:
    - navigation.expand
nav:
  - Introdução: index.md
extra:
  alternate:
    - name: Portuguese
      link: pt/ 
      lang: pt
    - name: English
      link: en/
      lang: en
plugins:
  - redirects:
      redirect_maps:
        'index.md': 'pt/index.md'